export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR"
export const USER_LOGOUT = "USER_LOGOUT";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
export const ADD_NEW_CATEGORY_ERROR = "ADD_NEW_CATEGORY_ERROR";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR"
export const DELETE_CATEGORIES = "DELETE_CATEGORIES";
export const GET_SPECIFIC_CATEGORY_DETAILS = "GET_SPECIFIC_CATEGORY_DETAILS";
export const GET_SPECIFIC_CATEGORY_DETAILS_ERROR = "GET_SPECIFIC_CATEGORY_DETAILS_ERROR";

export const GET_COURSES = "GET_COURSES";
export const GET_COURSES_ERROR = "GET_COURSES_ERROR";
export const ADD_NEW_COURSE = "ADD_NEW_COURSE";
export const ADD_NEW_COURSE_ERROR = "ADD_NEW_COURSE_ERROR";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const UPDATE_COURSE_ERROR = "UPDATE_COURSE_ERROR"
export const DELETE_COURSES = "DELETE_COURSES";
export const GET_SPECIFIC_COURSE_DETAILS = "GET_SPECIFIC_COURSE_DETAILS";
export const GET_SPECIFIC_COURSE_DETAILS_ERROR = "GET_SPECIFIC_COURSE_DETAILS_ERROR";

export const GET_TOPICS = "GET_TOPICS";
export const GET_TOPICS_ERROR = "GET_TOPICS_ERROR";
export const ADD_NEW_TOPIC = "ADD_NEW_TOPIC";
export const ADD_NEW_TOPIC_ERROR = "ADD_NEW_TOPIC_ERROR";
export const UPDATE_TOPIC = "UPDATE_TOPIC";
export const UPDATE_TOPIC_ERROR = "UPDATE_TOPIC_ERROR"
export const DELETE_TOPIC = "DELETE_TOPIC";
export const GET_SPECIFIC_TOPIC_DETAILS = "GET_SPECIFIC_TOPIC_DETAILS";
export const GET_SPECIFIC_TOPIC_DETAILS_ERROR = "GET_SPECIFIC_TOPIC_DETAILS_ERROR";

export const GET_CONTENTS = "GET_CONTENTS";
export const GET_CONTENTS_ERROR = "GET_CONTENTS_ERROR";
export const ADD_NEW_CONTENT = "ADD_NEW_CONTENT";
export const ADD_NEW_CONTENT_ERROR = "ADD_NEW_CONTENT_ERROR";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const UPDATE_CONTENT_ERROR = "UPDATE_CONTENT_ERROR"
export const DELETE_CONTENT = "DELETE_CONTENT";
export const GET_SPECIFIC_CONTENT_DETAILS = "GET_SPECIFIC_CONTENT_DETAILS";
export const GET_SPECIFIC_CONTENT_DETAILS_ERROR = "GET_SPECIFIC_CONTENT_DETAILS_ERROR";

export const USER_LOGIN_REQUIRED = "USER_LOGIN_REQUIRED";