const APP_STRING = {
    CHECK_ALL_VIDEOS: "Check all videos",
    SIGNUP: "Sign Up",
    LOGIN: "Login",
    EMAIL: "Email",
    PASSWORD: "Password",
    FIRST_NAME: "First Name",
    LAST_NAME: "Last Name",
    FIRST_NAME_PLACEHOLDER: "Enter your first name",
    LAST_NAME_PLACEHOLDER: "Enter your lasr name",
    EMAIL_PLACEHOLDER: "Enter your email",
    PASSWORD_PLACEHOLDER: "Enter your password",
    SUBMIT: "Submit",
    WATCH_COUNT: "Watch Count",
    LIKES: "Likes",
    DISLIKE: "Dislike",
    ONLINE_LEARNING_PLATFORM: "Online Learning Platform",
    SIGNUP_SUCCESS_MESSAGE: "You have successfully registered with us, please click below for login",
    COURSES: "Courses",
    STUDENT: "Student",
    ADD_NEW_CATEGORY: "Add New Category",
    WELCOME: "Welcome",
    CATEGORY: "Category",
    ADD_NEW_COURSE: "Add New Course",
    PRICE: "Price",
    FREE: "Free",
    COURSE_NAME: "Course Name",
    VIDEOS: "Videos",
    ADD_NEW_CONTENT: "Add new content",
    CONTENT_TITLE: "Content title",
    TEXT_MATERIALS: "Text materials",
    PDF_MATERIALS: "PDF materials",
    CATEGORY_NAME: "Category Name",
    CATEGORY_DESCRIPTION: "Category Description",
    PLACEHOLDER_CATEGORY_NAME: "Add Category Name",
    PLACEHOLDER_CATEGORY_DESCRIPTION: "Add Category Description",
    TITLE: 'Title',
    DESCRIPTION: "Description",
    ADD_CATEGORY: "Add Category",
    PLEASE_FILL_ALL_THE_DETAILS: "Please fill all the details.",
    EDIT_CATEGORY: "Edit Category",
    UPDATE_CATEGORY: "Update Category",
    COURSE_DESCRIPTION: "Course Description",
    UPDATE_COURSE: "Update Course",
    COURSE_PRICE: "Course Price",
    PLACEHOLDER_COURSE_PRICE: "Add Course Price",
    PLACEHOLDER_COURSE_NAME: "Add Course Name",
    PLACEHOLDER_COURSE_DESCRIPTION: "Add Course Description",
    ADD_NEW_TOPIC: "Add New Topic",
    UPDATE_TOPIC: "Update Topic",
    TOPIC_NAME: "Topic Name",
    TOPIC_DESCRIPTION: "Topic Description",
    PLACEHOLDER_TOPIC_NAME: "Enter Topic Name",
    PLACEHOLDER_TOPIC_DESCRIPTION: "Enter Topic Description",
    CONTENT_NAME: "Content Name",
    CONTENT_DESCRIPTION: "Content Description",
    CONTENT_URL: "Content URL",
    CONTENT_DESCRIPTION_DETAILS: "Text Content",
    PLACEHOLDER_CONTENT_NAME: "Add Content Name",
    PLACEHOLDER_CONTENT_DESCRIPTION: "Add Content Description",
    PLACEHOLDER_CONTENT_URL: "Add Content URL",
    PLACEHOLDER_CONTENT_DESCRIPTION_DETAILS: "Add Text Content",
    UPDATE_CONTENT: "Update Content",
    ADD_NEW_VIDEO: "Add new video",
    NO_CATEGORIES: "No categories available, please add new category.",
    ADD_CATEGORY_SUCCESS: "Category added successfully.",
    NO_COURSES: "No courses available, please add new course.",
    ADD_TOPIC_SUCCESS: "Topic added successfully",
    NO_CONTENT: "No content available, please add new content.",
    CATEGORIES: "Categories",
    BECOME_TRAINER: "Become trainer",
    CONTACT_US: "Contact us",
    FAQ: "Faq Page",
    SPONSER_PAGE: "Sponser us",
    JOIN_US: "Join us",
    SUPPORT: "Support"
}

// export const APP_BACKEND_URL = 'https://learning-app-backend.onrender.com';
export const APP_BACKEND_URL = 'http://localhost:5000'

export default APP_STRING;